### ISSUE TITLE
Basic SEO for kyma-project.io

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#100]
**Description**

First:
* We should do some basic optimization to be able to measure the effectiveness
* Try with official google recommendations for start
* Focus on search queries that we expect due to kyma name, technology stack and the mission statement:
  * `kyma` (github org is 4th, the kyma-project.io is 15th)
  * `extending enterprise software in cloud` (currently 46th result, in incognito, excluding advertisement items)
  * `extending enterprise software using kubernetes` (currently 4th result, in incognito, excluding advertisement items)

AC:
* After each improvement reindexing of the website must be triggered and after a week we need to check if there is any noticable change in the search results
* After completing the Epic we need to measure the traffic in google analytics if it improved comparing to previous months

Success measure:
- Better search position
- More traffic on kyma-project.io

**Reasons**

* Kyma is a new project in Kubernetes landscape and we need to enable kyma-project.io site to be much more visible in google search results. 
* People can end up directly on kyma-project.io only if they are attending some conference and learn about kyma. In majority of cases you find different projects that solve your problems by googling and reading about them. So google should be our focus and we should work on SEO
* Increase traffic on kyma-project.io to get more users

**Comment by derberg** [comment]
this is still valid

**Comment by mmitoraj** [comment]
Implementation is ready but we need information from @evilyeti regarding Google Search configuration. @derberg will track this issue and stay in touch with @evilyeti regarding this.
