### ISSUE TITLE
Introduce Structured Data to improve SEO

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#101]
**Description**

Get these features as basic ones
- Search as shown in below `pinterest` screen shot: https://developers.google.com/search/docs/data-types/sitelinks-searchbox
- Get social profile with all our social links that we also list on our website: https://developers.google.com/search/docs/data-types/social-profile
- Display logo, svg if possible: https://developers.google.com/search/docs/data-types/logo
- Info how to contact Kyma people: https://developers.google.com/search/docs/data-types/corporate-contact
- Basic info what kyma is
- Have highlight from twitter like on below screen shot that shows `pinterest`

**Reasons**

- improve SEO
- get better visibility of kyma in google search

**Attachments**

<img width="1274" alt="screen shot 2018-11-05 at 17 48 02" src="https://user-images.githubusercontent.com/6995927/48016425-dcdb4100-e12b-11e8-907f-b378081ca09b.png">

<img width="640" alt="screen shot 2018-11-05 at 17 48 25" src="https://user-images.githubusercontent.com/6995927/48016446-e664a900-e12b-11e8-8c51-734a8efae3f5.png">

<img width="677" alt="screen shot 2018-11-05 at 17 48 43" src="https://user-images.githubusercontent.com/6995927/48016466-f41a2e80-e12b-11e8-8b3a-6cf288a6f986.png">

**Comment by mmitoraj** [comment]
Implementation is ready but we need information from @evilyeti regarding Google Search configuration. @derberg will track this issue and stay in touch with @evilyeti regarding this.
