### ISSUE TITLE
Enable linking between documents

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#103]
**Description**

- Clear guideline about links and take inspiration from https://devportal.yaas.io/tools/documentationsdk/index.html#Linking-cross-linking-in-the-same-portal and https://devportal.yaas.io/tools/documentationguidelines/index.html#Linking:
  - why and how to link
  - how to add link to document from the same topic
  - how to add link to document from different topic
- solution must be communicated so others can start adding links
- whatever solution we choose we need to remember it must be supported by `milv` tool to validate links
- enable `chain` icon next to each header that shows up on hover, on click it links to given section so you get a direct link in the address bar of the browser. Check it out in action in GitHub or in our manifesto https://kyma-project.github.io/community. For website better use gatsby plugin https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/
- Update this document with proper relative links as a role model https://raw.githubusercontent.com/kyma-project/kyma/master/docs/kyma/docs/006-overview-how-to-start.md

**Reasons**

At the moment we do not use links between documents, because we would the have to agree to have broken links either in github or kyma-project.io

**Comment by magicmatatjahu** [comment]
Issue for `milv`: https://github.com/magicmatatjahu/milv/issues/11

**Comment by pkosiec** [comment]
Review: @pkosiec @michal-hudy
