### ISSUE TITLE
Expose product content more and enable easy contributions

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#105]
**Description**

- Provide `Edit` functionality in docs section that enables easy documentation contribution like https://kubernetes.io/docs/tasks/tools/install-kubectl/. After clicking Edit user should first get an overview info about contrib requirements for documentation (links to guidelines and templates) and then a direct link to github PR submission
- Have a place on landing page where we can introduce all different product content channels 

Success:
After implementation of each Epic's item we should measure if:
- amount of documentation contributions increased (number of PRs with `area/documentation` label)
- traffic on youtube (check insights from kyma channel), examples repo visitors increase and number of visits referred from kyma-project.io is increased (https://github.com/kyma-project/examples/graphs/traffic)

**Reasons**

- So far we have only docs section but in future we will have for example webinars from our releases, we also have examples in examples repo. kyma-project.io as entry point for new users to onboard on kyma should provide and overview of all locations of these different content channels
- It should be very easy to contribute to documentation

**Comment by derberg** [comment]
still on our bucket list

**Comment by pbochynski** [comment]
I think we should close it. It is relatively low priority.
