### ISSUE TITLE
Set up a chat bot 

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#106]
**Description**

- add a chat bot using https://recast.ai
  - work on content structure to make sure Conversational AI is useful
  - is should not only support docs but entire page, so not only questions like `How can I secure my lambda` but also `What is the next event where I can meet some kyma member`

**Reasons**
- follow trend of enabling conversational AI standards on a website to make it easier for the user to find relevant content

**Comment by derberg** [comment]
still on our bucket list

**Comment by pbochynski** [comment]
I think it is so low priority on our list that will not happen this year. Feel free to reopen if you want to contribute :)
