### ISSUE TITLE
Render more than just docs for official releases

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#126]
**Description**

- version switcher should contain not only latest and old releases but also `master` and release candidates
- integrate with CI pipelines as much as possible so it is an automated process where human is not really needed
- update README.md in /docs directory (add if not there) with clear disclaimer that github markdown files are just a source files and for reading they should be accessed on kyma-project.io/docs and in case of latest master mention that we also render ii in kyma-project.io/doc/master. @kazydek will help here

**Reasons**

We want kyma-project.io/docs to be a presentation layer while github and markdown files are only considered to be source files that devs should not read and navigate through different docs folders. To fully support such assumption we should also enable rendering of `master` version and `pre-release`

Documentation from RC should not be displayed if the RC has been released

**Comment by mjasinski5** [comment]
Review: @pkosiec

**Comment by pkosiec** [comment]
Review: @pkosiec @michal-hudy
