### ISSUE TITLE
Add the "Copy" button to the command fields in UI

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/website#134]
**Description**
Add the "Copy" button to the command fields in UI. It would be really convenient to copy the whole command with just one click. See the screenshot from [this](https://cloud.google.com/iam/docs/creating-managing-service-accounts#listing_service_accounts) site:

![copy button](https://user-images.githubusercontent.com/35192450/48897286-ebbf3480-ee49-11e8-956a-467bfe59d6b4.png)

**Reasons**
Adding such a button would make it easier to copy commands, which would greatly improve the user experience.

**Comment by klaudiagrz** [comment]
@derberg I've adjusted the issue to the template and attached the screenshot.

**Comment by klaudiagrz** [comment]
Thank you @ly1ila , that's what I was thinking of! @derberg Can we think of implementing this feature?

**Comment by derberg** [comment]
Let us do https://github.com/kyma-project/website/issues/20 first, then copy button. Deal?

**Comment by klaudiagrz** [comment]
Deal! 👍
