### ISSUE TITLE
Improve website styling to make working with documentation easier

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/website#137]
**Description**

The documentation base in Kyma is robust and detailed, covers multiple topics, and grows with every day. Being the easiest to access point of entry for the product documentation, the `kyma-project.io` website should make going through the product documentation as easy and productive as possible. 
In its current state, however, the styling used on the website makes it difficult to navigate the content and to know your current whereabouts in the content structure. 

The main issues are: 

1. The font size of the main content section is too big which forces the user to scroll a lot. 
2. The width of the main content section is too small which forces the user to scroll a lot and breaks up sentences unnaturally. This hampers the reading flow. 
3. The difference between heading types is indiscernible which makes navigating the sections confusing. 

**Reasons**

These changes should be introduced to improve what is, more often than not, the user's first contact with the product - its documentation. 

The suggested improvements are based on my own observations and testing (mainly viewing the website on different screens, devices, and OSes), as well as on developer feedback. 

**Attachments**

None

**Comment by derberg** [comment]
@antiheld it is not a first time I hear such feedback. Most common feedback is that font is to big and that we do not have such a nice particular docs separation like in the Docs UI in the Console.

@tomekpapiernik please remove number 4 as it is addressed by https://github.com/kyma-project/website/issues/24

**Comment by tomekpapiernik** [comment]
> @tomekpapiernik please remove number 4 as it is addressed by #24

@derberg Removed.

**Comment by derberg** [comment]
the width should be consistent with github width, so not 860 but 980

**Comment by derberg** [comment]
latest design, 
- more spacing between nav and content
- font made 16 not 20
- beter separation of sections
- width 1:1 consistent with github

![screen shot 2018-12-05 at 12 47 12](https://user-images.githubusercontent.com/6995927/49520802-5dfd3380-f8a4-11e8-8cc7-bfda009abc72.png)

**Comment by derberg** [comment]
the width should be improved not only kyma-project.io/docs but also:
- kyma-project.io/blog 
- the docs-ui in console
- catalog and instance ui

**Comment by mjasinski5** [comment]
Review: @pkosiec @akucharska
