### ISSUE TITLE
Broken links in "How to start" section for Kyma 0.5 docs

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/website#139]
**Description**
The links are broken in the 'How to start section' on Docs page.
Some links redirect to  https://kyma-project.io/docs/latest/root/kyma#getting-started-local-kyma-installation

Can you, please. fix this bug and provide relevant links?

Thanks,
Ana

**Comment by pkosiec** [comment]
Hi @anajankovic,
Could you please point which links are broken? Thanks!

**Comment by anajankovic** [comment]
See the links on the screenshot below.
![image](https://user-images.githubusercontent.com/40662246/48999676-a8213f00-f157-11e8-98bb-71b8555867f7.png)

**Comment by pkosiec** [comment]
Please next time provide URL as well 🙂

Anyway, I found them: https://kyma-project.io/docs/latest/root/kyma#overview-how-to-start
However, to fix them, we would need to release a new 0.5.X version of Kyma...

**Comment by pkosiec** [comment]
Review: @pkosiec @michal-hudy
