### ISSUE TITLE
Logos on the kyma landing page

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/website#178]
Hello,

We need to insert the logos attached to the Kyma landing page.

Location: Below the community part
Title: Early adopters
Logos should be placed in one line. 

![image](https://user-images.githubusercontent.com/40662246/50899146-94811d80-1411-11e9-88c0-3ebf5a3602f4.png)
![image](https://user-images.githubusercontent.com/40662246/50899173-a95db100-1411-11e9-8c15-16edace15c9f.png)
![image](https://user-images.githubusercontent.com/40662246/50899378-36086f00-1412-11e9-822c-279255dc9f05.png)
![image](https://user-images.githubusercontent.com/40662246/50899446-7536c000-1412-11e9-9cf2-4f7cd2601ac1.png)

**Comment by derberg** [comment]
Make sure to use svgs and not png. They all should be publicly available as I quickly found svg for netconomy: https://www.netconomy.net/content/themes/netconomy/dist/images/NC-Logo.svg

**Comment by anajankovic** [comment]
Add the SAP logo too
file:///C:/Users/d072939/Desktop/SAP_grad_RZeichenfläche%201.svg

**Comment by derberg** [comment]
@anajankovic link points to your local disk. If this is the one you wanted to point out, we are covered: https://help.sap.com/viewer/_build_6a1cc2a53e4ad2501a7f19ac/img/sap.svg

**Comment by ly1ila** [comment]
Here are the logos as SVG in the right sizes: [Logos Kyma Case Studies.zip](https://github.com/kyma-project/website/files/2767813/Logos.Kyma.Case.Studies.zip)

Integration into the landing page:

![kyma_lp_user-cases-logos_190116_snippet](https://user-images.githubusercontent.com/25120433/51307552-4fc43a80-1a40-11e9-8654-b68eeeb5d195.png)

**Comment by anajankovic** [comment]
@ly1ila can you, please upload the background of the logos on the landing page to Zeplin? The team is working on the implementation.

**Comment by ly1ila** [comment]
@anajankovic
[BG_kyma_Logo_section.zip](https://github.com/kyma-project/website/files/2855526/BG_kyma_Logo_section.zip)
