### ISSUE TITLE
Left navigation bugs - bites into footer, doesn't allow to collapse topics

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/website#187]
**Description**

1. When scrolling using a mouse with a physical scroll wheel (i.e. not the MagicMouse), you can make the navigation area "bite" into the footer. See the attached screenshot. 
![image](https://user-images.githubusercontent.com/29116492/51538881-b38ca000-1e52-11e9-8591-778e6dc33f82.png)

2. You can't collapse the topic when you're viewing a document it contains. The UI graphics suggest it should be possible. 
Example: 
- 
![image](https://user-images.githubusercontent.com/29116492/51539047-4299b800-1e53-11e9-916e-ddfbea127de0.png)

- click: 
![image](https://user-images.githubusercontent.com/29116492/51538860-a4a5ed80-1e52-11e9-8841-1e46dfabe951.png)

**Comment by derberg** [comment]
@tomekpapiernik @magicmatatjahu is it still valid?

**Comment by magicmatatjahu** [comment]
Still valid

**Comment by magicmatatjahu** [comment]
Closed by https://github.com/kyma-project/website/pull/413
