### ISSUE TITLE
Use gatsby-plugin-catch-links to limit refreshing pages while navigating from blogposts

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/website#189]
**Description**

Improve user experience when using links from blogposts. The plugin intercepts local links uses `Link` component from `gatsby`, which will prevent page reloading.

Read more: https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/

**Reasons**

By installing a simple plugin,  we will get SPA experience for navigating between blogposts to docs or other places of the website.

**Comment by magicmatatjahu** [comment]
Already we use another solution for that. Close.
