### ISSUE TITLE
Better exposure of community contact links

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#19]
**Description**

- Add a new section to the website that introduces the community 

```
**Community**

Kyma is the open source project with an active and vibrant community supporting the Kyma development and drive it forward.

We invite you to get involved with the Kyma community!

Follow Kyma on [Twitter](https://twitter.com/kymaproject) and [LinkedIn](https://www.linkedin.com/company/kyma-project/) to get the latest news

Join [Slack](https://join.slack.com/t/kyma-community/shared_invite/enQtNDAwNzE4Mjk2NDE3LTJhOTlmZjM5YzkwNmEzNmY3ZjE2MTU2OTMxOGE4ZDM0MmU4ZWRkZGJiODgzNmRmMTYxMDYwNjZiMDAwMTA2OWM) for a general discussion, exchange ideas and get hints &amp; tricks from experts.

Join Kyma on [GitHub](https://github.com/kyma-project) to report issues and bugs, review documentation and read use cases.

If you´d like to contribute to the Kyma project, participate in our [Special Interest Group](https://github.com/kyma-project/community).
```

**Reasons**

Make sure community can quickly access all channels maintained for kyma community

**Comment by derberg** [comment]
@anajankovic we cannot proceed with the ticket yet. During sprint planning my team pointed out that current design of the kyma-project.io page clearly requires some picture per section. Also, because of the design when once we have white background and then blue-wave, it is hard to add some new section, if we do it after last section and before footer, what background to do? blue and change footer to white? I hope you know what I mean, we need a clear design here

**Comment by anajankovic** [comment]
I will brief the SNK. Thank you.

**Comment by anajankovic** [comment]
I have attached to the JIRA issue  https://jira.hybris.com/browse/YSF-3010 the preview of the community section - please follow the content for the community section written on this preview. 

Additional comments: 
- Special Interest Group to be linked to https://github.com/kyma-project/community
- GitHub to be linked to https://github.com/kyma-Project
- Twitter to be linked to https://twitter.com/kymaproject
- Slack to be linked to https://join.slack.com/t/kyma-community/shared_invite/enQtNDAwNzE4Mjk2NDE3LTJhOTlmZjM5YzkwNmEzNmY3ZjE2MTU2OTMxOGE4ZDM0MmU4ZWRkZGJiODgzNmRmMTYxMDYwNjZiMDAwMTA2OWM
-LinkedIn to be linked to https://www.linkedin.com/company/kyma-project/

Thank you!

**Comment by anajankovic** [comment]
SAP Customer Experience LIVE Hackathon - link https://events.sap.com/sap-cx-live/en/hackathon-live
SAP Customer Experience LIVE - link https://events.sap.com/sap-cx-live/en/home

**Comment by anajankovic** [comment]
Hi,

We need to update the text in the 'What is Kyma?´ section. Please, see the content attached.
Also, there is improvement in the illustrations for 'What is Kyma?' and 'Kyma Mission' sections, see the landing page preview. 

Thank you!  
![kyma-landingpage illustration update](https://user-images.githubusercontent.com/40662246/45282747-1e5cc080-b4dc-11e8-9167-f7467d5c44c4.png)
[What is Kyma section text improvement.docx](https://github.com/kyma-project/website/files/2365572/What.is.Kyma.section.text.improvement.docx)

**Comment by antiheld** [comment]
Here are the new Illustrations for the Landingpage
[SVGs.zip](https://github.com/kyma-project/website/files/2367463/SVGs.zip)

**Comment by derberg** [comment]
@anajankovic to speed up development a bit and not keep it hanging forever as changed the scope of this ticket to handle only new community section. In this separate ticket that we will do now this sprint you can see that we will at least address the links exposure https://github.com/kyma-project/website/issues/31

**Comment by anajankovic** [comment]
@derberg In the community section we need to have Icons of all Kyma community channels:

GitHub Icon https://github.com/kyma-project
Twitter Icon https://twitter.com/kymaproject
Slack Icon  https://join.slack.com/t/kyma-community/shared_invite/enQtNDAwNzE4Mjk2NDE3LTJhOTlmZjM5YzkwNmEzNmY3ZjE2MTU2OTMxOGE4ZDM0MmU4ZWRkZGJiODgzNmRmMTYxMDYwNjZiMDAwMTA2OWM 
LinkedIn Icon https://www.linkedin.com/company/kyma-project/

see the community section preview. Also, we need to remove the social media Icons from the footer since now we have all of them in the community section. 

and yes we need to add Slack button on top next to GitHub and link to self sign up https://join.slack.com/t/kyma-community/shared_invite/enQtNDAwNzE4Mjk2NDE3LTJhOTlmZjM5YzkwNmEzNmY3ZjE2MTU2OTMxOGE4ZDM0MmU4ZWRkZGJiODgzNmRmMTYxMDYwNjZiMDAwMTA2OWM

**Comment by mjasinski5** [comment]
Review: @michal-hudy @akucharska
