### ISSUE TITLE
Introduce different color panels on UI

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/website#191]
**Description**

As discussed on the SIG Content, we noticed that different color panels would be helpful to grab the users' attention when they read the Kyma documentation. For now, we only have NOTE to highlight some issues, but **Caution** and **Tip** would also be useful.

Apart from the technical implementation, the documentation will also have to be updated. It would be helpful to create a document in the `community` repo that explains how to add such panels in the documentation and when to use them.

**Reasons**

This implementation will not only improve the user experience but it will also allow us to focus users' attention on matters that we'd like to highlight. 

**Attachments**

These are the exemplary panels used on the [Yaas website](https://devportal.yaas.io/tools/documentationsdk/index.html#Panels). As discussed on the SIG Content, apart from Notes that we already have, we'd be interested in **Caution** and **Tip**. 

![panels](https://user-images.githubusercontent.com/35192450/51986847-70a97880-24a1-11e9-8592-f214e5f9c8dc.png)

Find the descriptions of different UI Panels in the [official SAP documentation](https://help.sap.com/viewer/DRAFT/e33c591ae4494a659a3f5f983c9d1161/PROD/en-US/bc7ef30971c04857b5d7cb50193065c1.html).

**Comment by magicmatatjahu** [comment]
Hi Klaudia!
The technical implementation will very easy after completing issue: https://github.com/kyma-project/website/issues/196 So stay tuned 😄

**Comment by klaudiagrz** [comment]
@magicmatatjahu I'm more than happy to hear that! :)

**Comment by ly1ila** [comment]
Hi @klaudiagrz, 

here are the colors defined for the panels:

For the **kyma-project.io/docs/**  

[Uploading kyma-io_docs_color-panels.png…]()

Warning: `#DD0000`
Tip: `#49C7A0`

For the **console**

[Uploading kyma-console_docs_color-panels.png…]()

Warning: `#BB0000`
Tip: `#107E3E`

**Comment by aerfio** [comment]
Note to self: discuss whether we'll use 3 or 4 colors
