### ISSUE TITLE
Cropped bad thumbnails of Kyma on social websites

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/website#199]
**Description**

When you paste https://kyma-project.io link into Facebook and social websites, the thumbnail is a cropped bad image of Kyma logo. Looks very unprofessional.

**Expected result**

A scaled, proper thumbnail of Kyma logo.

**Actual result**

![screen shot 2019-02-12 at 01 07 24](https://user-images.githubusercontent.com/1930204/52603123-bb45d000-2e65-11e9-8ad7-7b0ccfa18ef4.png)

**Steps to reproduce**
- Paste a link of https://kyma-project.io in Facebook post. 
- Checkout the result thumbnail

**Comment by anajankovic** [comment]
On Twitter the Kyma logo is displayed fine. But, not on LinkedIn. See the screenshot below.

![image](https://user-images.githubusercontent.com/40662246/52618721-df260780-2e9f-11e9-879d-7f6eb3b53dc7.png)

**Comment by pkosiec** [comment]
Hi @Abd4llA and @anajankovic,
Thanks for reporting that. Unfortunately, Facebook and LinkedIn do auto-cropping for site metadata images. We will need to replace the image with a horizontal one.

**Comment by magicmatatjahu** [comment]
Still valid
