### ISSUE TITLE
Create documentation toggle - content dependent on chosen OS

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#20]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Implement a toggle that would enable us to show the user documentation relevant for the OS he uses.
- decide how it should be handled on a backed side, div with specific class?
- document how to use this feature in markdown files
- have this toggle/tab view in kyma-project.io/docs and content-ui

**Reasons**

Limit length of documents and display instructions only for relevant OS for the user

**Attachments**

designs tbd

**Comment by derberg** [comment]
@antiheld Hey man, please add designs here once you have them

**Comment by derberg** [comment]
/remind @antiheld to provide design for os toggle in 3 weeks

**Comment by klaudiagrz** [comment]
This feature would be helpful not only for different OS documentation but also in docs we currently have. For example, we have Kyma installation on GKE cluster and AKS cluster which only have different commands (and also other providers will be added in the future). 

![toggle](https://user-images.githubusercontent.com/35192450/51259670-e6471c00-19ac-11e9-84ac-933f1723086f.png)

Toggle would also be useful in case of local vs. cluster installation -> this would make installation documents more clear and user-friendly. 

@magicmatatjahu @derberg Could you kindly think of the toggle implementation and examples on how we would use it in docs? It would be perfect if you could show us some options on the next SIG Content, on Wednesday, Jan, 23 at 2:30 pm.

**Comment by magicmatatjahu** [comment]
Hi @klaudiagrz. One of option to use is a collapsible section - more info and examples [here](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab), but probably our tools for rendering markdown to html cannot handle it, so we will have to write some extra parser or using other tools. The another solution is using syntax like this (only for code blocks) PLEASE SEE RAW CONTENT:
``` python label="Python 2"
print "Bonjour" 
```

``` python label="Python 3"
print("Bonjour")
```
So first codeblock will be for first tab and second for second like this:
![image](https://user-images.githubusercontent.com/20404945/51264687-5d81ad80-19b7-11e9-8c79-c57639262ddf.png)

For me, first solution is better because in the near future we will be write custom react components for docs in website as in content-ui, so we could handle this problem here.

**Comment by derberg** [comment]
I'm not a fan of collapse/expand for these use cases. Collapse/expand is if you want to hide content that is not must read but something additional.

For this use case the only option is tabs like https://cloud.google.com/iam/docs/creating-managing-service-accounts#listing_service_accounts

We only need to align how to put the content in markdown so it is easier later to parse in the frontend and display in tabs. One of the options is something I noticed here https://raw.githubusercontent.com/SAPDocuments/Tutorials/38ebc0ff01f3d1d18b422b92fe97547b84cf5209/tutorials/cp-cf-rabbitmq-create-service/cp-cf-rabbitmq-create-service.md (square brackets pattern `[SOMETHING]`) where they solve structuring of content for accordion view visible here https://developers.sap.com/tutorials/cp-cf-rabbitmq-create-service.html
It introduced some custom approach in markdown, but I don't have a better idea how to do it in a clean way for content provider as well

**Comment by ly1ila** [comment]
Styling for tab:
[kyma-io_tab_markdown](https://user-images.githubusercontent.com/25120433/53734406-2cd0d700-3e84-11e9-8739-07675d2749bb.png)

Font: 16px (default p) Inactive: #485766 ; Hover/Active: #0B74DE
Tab Active:  border 3px, Color: #0B74DE

**Comment by derberg** [comment]
@ly1ila thanks a lot for that! only one remark is that the tab should start with indentation, so it is not right below the number, to keep the flow

what I mean is that instead:
```
1. this is some text:
tab component is rendered here
```

it should be:
```
1. this is some text:
   tab component should be indented a bit
```

**Comment by ly1ila** [comment]
Thank you, @derberg. Here is the update: 
[Uploading kyma-io_tab_markdown_update.png…]()
