### ISSUE TITLE
Create script for creating generic content for social media

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#208]
**Description**

At this moment the website is created with the static pages. By this, we can write program/script for creating generic content for social media - eg. facebook, linkedin, twitter - mainly thumbnails. 

Each blog post and each documentation should have a separate one thumbnail - currently we have one static for all pages, which is sometimes cut (see #199). 

My proposition:
- create script in `gatsby` folder for `onPreBuild`, `onPreBootstrap` or `onPreInit` Gatsby lifecycle ([documentation](https://www.gatsbyjs.org/docs/node-apis/#onPreBootstrap)) for creating generic content for social media - mainly thumbnails.
- use one of node.js library for paste to image text described content on page:
  - for blog post title of post
  - for docs template: Kyma documentation `{version}` - `{docTopic - eg. Service Catalog}`
- use as fallback default thumbnail.

**Reasons**

Currently, the thumbnail is pruned and it does not look aesthetic. 

**Related issues**:
- #199

**Comment by magicmatatjahu** [comment]
Still valid

**Comment by derberg** [comment]
@magicmatatjahu do you agree to close it, I don't think it is very important task, or lable as good first issue?

**Comment by valentinvieriu** [comment]
Still Valid!

Besides having the image automatically generated, we should have propper open graph title and description that fit the blog post or document. At this moment we get the generic ones from the website

![image](https://user-images.githubusercontent.com/478866/81905985-cc7c1000-95c5-11ea-8aa9-20d2009d42ba.png)
