### ISSUE TITLE
Fetch documentation from kyma repository on building time website

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#213]
**Description**
At the moment we have documentation for all version in `static/documentation` folder. This is unnecessary, and causes `Kyma-bot` top of contributor. 

AC:
- create stage for fetching documentation on time building website on one of Gatsby's lifecycles - the best will be `OnPreBuild` or suggest something better.
- create mocks of documentation for development process.
- remove all generated documentation version from sources of website.

**Reasons**
- Eliminate `Kyma-bot` from contributors 😈

**Comment by derberg** [comment]
consider switching from GH Pages to https://www.netlify.com/
it is gaining in popularity and has amazing features that make it worth trying https://www.netlify.com/github-pages-vs-netlify/ (one click rollback or deploy preview is super nice)
We could easily apply https://www.netlify.com/legal/open-source-policy/
