### ISSUE TITLE
Change behaviour of the navigation and always display "type" metadata as first

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#23]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Change behaviour of navigation this way that if you have one doc of some `type`, it should anyway be displayed. So let us assume you have one document with `title` Installation and `type` Custom Resource, then this is how it should look like in navigation:
```
+ Custom Resource
         Installation

NOT

Installation
```
- Investigate how is it connected to but that links to hrefs are duplicated and `type` is used as default value, not `title` -> example `#custom-resource-custom-resource`

**Reasons**

Not from the UI it is hard to determine that you are reading a document about custom resource https://kyma-project.io/docs/latest/root/kyma#custom-resource-custom-resource
same in case of other types of docs, if you for example would have only one getting started

**Comment by derberg** [comment]
The only problem is the Overview docs, that have the same title and type

**Comment by pkosiec** [comment]
Review: @magicmatatjahu @kazydek
