### ISSUE TITLE
Bad rendering of >**NOTE:** in documentation

### ISSUE THREAD

**Issue by aerfio** [kyma-project/website#236]
**Description**

Sometimes docs get pulled under previous component, which results in bad rendering

**Expected result**

Good rendering of docs, like here: 
![image](https://user-images.githubusercontent.com/17271979/54023162-898a0580-4194-11e9-8418-e5ef5cfe6b10.png)

**Actual result**

https://kyma-project.io/docs/components/application-connector#tutorials-trigger-a-lambda-with-events-steps
vs
https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/08-05-trigger-lambda-with-event.md#steps

https://kyma-project.io/docs/components/application-connector#tutorials-call-a-registered-external-service-from-kyma-steps
vs 
https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/08-06-call-registered-service-from-kyma.md#steps

**Steps to reproduce**

This happens when there's no new line after some text and before `>**NOTE**` (or any other text, see #191), or space before >**NOTE**

Lack of space or enter could result in such cases:
1: ![image](https://user-images.githubusercontent.com/17271979/54024245-82b0c200-4197-11e9-9b1b-63c653547e57.png)
2: ![image](https://user-images.githubusercontent.com/17271979/54024254-8a706680-4197-11e9-81c8-968fa1ca0190.png)
3: ![image](https://user-images.githubusercontent.com/17271979/54024259-90fede00-4197-11e9-846b-e7215c4b4274.png)
4: ![image](https://user-images.githubusercontent.com/17271979/54024269-978d5580-4197-11e9-9f18-b9efc9fe0314.png)

**Troubleshooting**

**Comment by aerfio** [comment]
So far we have seen such a thing only when there's a list, then note(in future also tip/caution)

**Comment by aerfio** [comment]
Update: border of `<code/>` block was fixed by #234

**Comment by mmitoraj** [comment]
Preview: https://deploy-preview-442--kyma-project.netlify.com/docs/note/root/kyma/
