### ISSUE TITLE
Add scroll spy

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#24]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

- Add typical navigation scroll spy like you can see here https://devportal.yaas.io/services/beta/product/v2/
- investigate why there is this strange delay in collapsing the nav node that looses focus once you click another nav node
- result of this issue answers question:
  - how to implement scroll spy and how much time it will take
  - how to do it properly so it is not always a double-work to do something in docs-ui and website

**NOTE**: Do it also on `content-ui`.

**Reasons**

With approach everypageispageone it is hard to keep on going with reading when the whole content is on one page. This needs to be handled by a scroll spy solution that always clearly indicated in what part of the UI you are located while reading.

**Comment by derberg** [comment]
This is still a valid backlog item

**Comment by pkosiec** [comment]
Review: @akucharska @pkosiec
