### ISSUE TITLE
Provide clear development guide

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#25]
**Description**

- How can I contribute? how to add features? how to write blog post? how to add documentation -> kyma/docs? how to modify content on the landing page? 
  - in blog instruction explain how to add images (where to store them and how to embed in markdown ) and how to link to other blog posts and docs
- dev guide structure must be consistent with guides that are already provided in kyma and console repos
- What is the project structure and what changes go where
- What are requirements of good contribution
- Step by step instruction of how to develop and what parts to do when
- How docs part is populated with data from kyma/docs
- How to contribute as a blog provider or content provider? how to get my things on kyma-project.io

**Reasons**

kyma-project.io needs constant improvement and development. It must be clear how to contribute so we can enable others to help

**Comment by pkosiec** [comment]
Review: @kazydek @pkosiec

**Comment by aerfio** [comment]
https://github.com/kyma-project/kyma/pull/1243
https://github.com/kyma-project/website/pull/50
