### ISSUE TITLE
Create a view of kyma roadmap

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#258]
**Description**

- due to the irregular quality of Epics  and lack of final vision for all capabilities page should not be yet visible in the navigation, we should see it only with direct URL for review
- content for visions should be taken from https://github.com/kyma-project/community/tree/master/capabilities (feel free to reorganize or introduce some index file to make it easy to fetch)
- dynamic display of roadmap means calling GitHub and ZenHub API and the number of API calls is limited. It can be done on a pipeline level, we do not need real-time refresh, set up the pipeline to periodically refresh the page as often as the limits allow us to do that.

**Reasons**

Have nice to digest, scalable and dynamic solution to share Kyma roadmap

**Attachments**

Designs are too big and not so easy to make a screenshot, just pick it up during implementation from the system

**Comment by sandra-snk** [comment]
Hi, find attached the Capabilities SVGs 
[Capabilities_page_icons.zip](https://github.com/kyma-project/website/files/3057705/Capabilities_page_icons.zip)
