### ISSUE TITLE
Add logo to the early adopters section

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/website#262]
**Description**

Add the logo to the early adopters section on the Kyma landing page.

Find the logo in svg format on this link https://sap.sharepoint.com/:u:/r/sites/100093/Shared%20Documents/Product%20Corner/Knowledge%20Management/Kyma%20Open%20Source/ARITHNEA-Logo.svg?csf=1&e=svMjUm

**Comment by magicmatatjahu** [comment]
Hello @anajankovic! Can you paste this logo as svg in zip in this thread? I have a problem with entering to site you gave.

**Comment by anajankovic** [comment]
Here it is.
[ARITHNEA-Logo.zip](https://github.com/kyma-project/website/files/3078759/ARITHNEA-Logo.zip)
