### ISSUE TITLE
Copy to clipboard issue

### ISSUE THREAD

**Issue by jcawley5** [kyma-project/website#263]
The following page has a bunch of commands listed that are proceeded with "$".  When using the "copy to clipboard" feature these are copied over resulting in an invalid command.

https://kyma-project.io/docs/components/serverless#cli-reference-cli-reference-details

Example

$ kubeless function list hello

should be listed as

kubeless function list hello

**Comment by magicmatatjahu** [comment]
Hello @jcawley5! Thanks for reporting bug. I already create PR with fixed it and other issue with copy button - copy `<` as `&#60;`. Sorry for problems with using **Kyma**.

We will try to merge it as quickly as possible.
