### ISSUE TITLE
Kyma website blog page - topics

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/website#27]
Hi, 

It would be great if we could add blog topics on the right side on the page https://kyma-project.io/blog.
These topics should be linkable so once a visitor clicks on a certain topic it takes him/her to that specific blog. Also, it would be good to display a publication date next to each blog topic.

Thank you,
Ana

**Comment by derberg** [comment]
Just to clarify, this would be a typical blog navigation with topics grouped by years, like https://kubernetes.io/blog/ with newest on top of course. I think we could reuse current left nav from docs here, and for now keep this on the left like istio https://istio.io/blog/2018/, or is there a strong requirement to keep it on right side? I would prefer to be consistent with the position of the navigation

**Comment by derberg** [comment]
Nav example:
- 2018
  - (10.08) Kyma and Knative Integration - Progress Update
  - (24.07) Introducing project Kyma
- 2017

**Comment by anajankovic** [comment]
I am fine with having the topics listed on the left side. I agree we should be consistent with the Docs page. 

Nav example: 

2018 
Kyma and Knative Integration - Progress Update, Aug 10
Introducing project Kyma, July 24

**Comment by derberg** [comment]
Still valid

**Comment by anajankovic** [comment]
Still valid.

**Comment by anajankovic** [comment]
Still valid.

**Comment by anajankovic** [comment]
Still valid.
