### ISSUE TITLE
Tags in kyma-project.io are not clickable and do not serve their purpose

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/website#275]
**Description**

You cannot click any of the tags that are added to blog posts to show other posts tagged with the same tag. This makes the tags pretty much useless. 

![image](https://user-images.githubusercontent.com/29116492/56806518-6bec2a80-682c-11e9-8149-15896bbe99c8.png)

**Expected result**

Each of the tags is a hyperlink. When clicked it shows all posts that are tagged with the given tag (such as #release-notes).

**Actual result**

Can't click tags, no filtering available. 

NOTE: I'm not sure whether this is a bug or such feature is not implemented.

**Comment by magicmatatjahu** [comment]
@tomekpapiernik Hi Tomek! This is not a bug, but feature which is not yet implemented. We will implement this within a few weeks.

**Comment by valentinvieriu** [comment]
this is not stale
