### ISSUE TITLE
Add kyma-project.io to showcase list in gatsby.org

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#284]
**Description**

As in title.

AC:
- Fill fields described [here](https://www.gatsbyjs.org/contributing/site-showcase-submissions/)
- Contribute to gatsby.org

**Reasons**

Let the world hear about **KYMA**!

**Comment by derberg** [comment]
PR created https://github.com/gatsbyjs/gatsby/pull/13936

**Comment by magicmatatjahu** [comment]
PR gatsbyjs/gatsby#13936 is merged.
