### ISSUE TITLE
Create contributing view

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#286]
**Description**

- Create contributing view (as another section in website, next of roadmap and community sections).
- Content should be fetch from community repo (and also from other our repositories if we need) in `content-loader-tool` from `guidelines` folder.

**Reasons**

A lot of another open-source projects from cloud-native world have a contributing sections in their sites, so we also should create the another one. This is also good idea for our developer, because from website they faster get interesting content.

Related issue on community repo: https://github.com/kyma-project/website/issues/356

**Comment by derberg** [comment]
duplicating https://github.com/kyma-project/website/issues/356
