### ISSUE TITLE
Enable navigation between tabs

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#301]
**Description**

At the moment, we cannot use links between tabs, eg: we have a two tabs, for installation Kyma on gcp and azure, and we want link from first tab to second, so we have to embrace a way to enable this functionality. One of a problem with this issue is that we generate static pages with gatsby, so in redirect we lose condition (state) from previous page...

AC:
- enable navigation between tabs:
  - if solution will be complicated, please also create/update relevant document [here](https://github.com/kyma-project/community/tree/master/guidelines) 
  - talk with TWs to support links in relevant docs [here](https://github.com/kyma-project/kyma/tree/master/docs)

**Reasons**

Better UX using documentation on our website.

**Comment by mmitoraj** [comment]
Add a name to tabs in each and every document
