### ISSUE TITLE
Create archive docs pages for old versions of Kyma

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#303]
**Description**

AC:
- Create archive view (or subdomain) for documentation of old version of Kyma:
  - talk with @derberg which versions should be treated as current - eg. two previous, or three previous?
  - prepare information with TWs about no longer support older version and add this above the docs in archive view.
  - look how Kubernetes it makes and create similar solution to that.

**Comment by derberg** [comment]
Not needed, we just do not keep old docs as they are not needed
