### ISSUE TITLE
Provide links to slack and linkedin

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#31]
**Description**

- Add `LinkedIn` icon to the footer and link to https://www.linkedin.com/company/kyma-project/
- Add `YouTube` icon to the footer and link to kyma channel https://www.youtube.com/channel/UC8Q8bBtYe9gQN-dQ-_L8JvQ
- Add `Slack` button on top next to GitHub and link to self sign up https://join.slack.com/t/kyma-community/shared_invite/enQtNDAwNzE4Mjk2NDE3LTJhOTlmZjM5YzkwNmEzNmY3ZjE2MTU2OTMxOGE4ZDM0MmU4ZWRkZGJiODgzNmRmMTYxMDYwNjZiMDAwMTA2OWM

**Reasons**
Make sure community can quickly access all channels maintained for kyma community

**Attachments**

[LinkedIn.zip](https://github.com/kyma-project/website/files/2322655/LinkedIn.zip)
[joinslack.zip](https://github.com/kyma-project/website/files/2326889/joinslack.zip)
[Youtube.svg.zip](https://github.com/kyma-project/website/files/2376004/Youtube.svg.zip)

**Comment by pkosiec** [comment]
Review:  @pkosiec @akucharska
