### ISSUE TITLE
Add functionality for a banner to promote different event where Kyma is present

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#32]
**Description**

- This must be done in the way that anybody with HTML knowledge can add the banner and decide when it should be visible and when should disappear.
- Do it through Yaml. Something like
  - title is a clickable link and page opens in another tab
  - icon is not mandatory, no fallback in place
```
title*: Join us for the Open Source Summit, Vancouver, August 28-30
link*: {URL}
icon(optional): {URL}
startDate: {defined date format}
endDate: {defined date format}
```
- clearly describe in readme:
  - how to use this functionality (when working on structure remember that in future we will also have to describe how to contribute to blogs section)
  - limits for title length 
  - requirements for icon
  - date format description
- check if maybe we can also quickly validate the pull request with such yaml to speed up PR processing
- add @anajankovic for the review so she can approve if all the instructions are understandable and if she likes the solution. Onboard Ana to the process of review please, how that works in GitHub
- in case of more then one event at the same time, scale with sliding effect like in typical carousel. Screenshot below. 2sec transition between events
- extended requirement:
     - be able to define target blank or not in case you have a relative link to a blog post that is inside the kyma-project page

**Reasons**

Make sure community knows where to find us on all possible meetups/conferences

**Attachments**

top of the [Kyma landingpage Illustration Update.zip](https://github.com/kyma-project/website/files/2365993/Kyma.landingpage.Illustration.Update.zip)

scaled baner ![screen shot 2018-09-24 at 09 40 27](https://user-images.githubusercontent.com/6995927/45941436-71576d00-bfde-11e8-8c3b-b2441694f120.png)

**Comment by derberg** [comment]
@anajankovic please take a look on this issues, if all is ok with the requirements, or you want something else. We didn't have issue for that yet as designs for banner were not there yet

**Comment by anajankovic** [comment]
@derberg We need to change the text on the banner:

Join us for the SAP Customer Experience LIVE Hackathon, Barcelona, October 9 & SAP Customer Experience LIVE, Barcelona, October 10-11

links: 
SAP Customer Experience LIVE Hackathon - link https://events.sap.com/sap-cx-live/en/hackathon-live
SAP Customer Experience LIVE - link https://events.sap.com/sap-cx-live/en/home 

I will check when are banners going to be finalized.

**Comment by derberg** [comment]
Don't worry about the text, in description of the ticket it is just an example, we work on solution that you will be able to add such banners on your own, whenever you want.

Important is that the banner is now set to accept one link. So one file per event. 

@antiheld any ideas how we could scale the banner in case we have situation described by Ana? that there are 2 events at the same time? do one banner under another? enable `x` icon to close the banner?

**Comment by antiheld** [comment]
Please have a look at the sliding event component on Zeplin: https://zpl.io/bJv8YeJ

**Comment by mjasinski5** [comment]
Review: @akucharska @pkosiec

**Comment by aerfio** [comment]
https://github.com/kyma-project/website/pull/96

**Comment by mjasinski5** [comment]
review: @pkosiec @kazydek
