### ISSUE TITLE
Implement feedback system

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/website#323]
**Description**

Currently, people who use the documentation on kyma-project.io, don't have any way to let us know if the docs help them and provided the information they were searching for or if they need to be improved. 

If the website had a feedback system, the user could: 
- thumb up/down a document
- leave a written note saying what is wrong and (hopefully) how to fix it; it'd be great to have a bot that would create appropriately labeled issues in GitHub when users leave such suggestions

Implementing such a system would empower the community. Not everybody has time to chat on Slack. (@derberg )

**Reasons**

The only sources of documentation-centered feedback are people who work with the project on a daily basis. There is very little feedback from newcomers and people who are not familiar with Kyma. 

**Attachments**

none

**Comment by magicmatatjahu** [comment]
Related issue: https://github.com/kyma-project/website/issues/105

**Comment by derberg** [comment]
thumbs up/down do not help much, but next to the edit button that we plan with https://github.com/kyma-project/website/issues/105 we could have a feedback button or something like that that would take user to github issues -> https://github.com/kyma-project/kyma/issues/new/choose

we could track the usage with google analytics, if we would see many people click the feedback button but then do not create issues, we could consider adding a dedicated feedback form that would then create a github issue with proper labels, etc

**Comment by pbochynski** [comment]
I think we can live with github issues and slack for now. No plans to implement it in the near future.
