### ISSUE TITLE
Write own React component for rendering markdown

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#325]
**Description**

As in title.

**Reasons**

We use at the moment [this](https://github.com/rexxars/react-markdown) component and we have a lot problems with it, eg:
- render code blocks
- render tabs
- render notes

**Comment by derberg** [comment]
already handled by generic component that will be reused in any Kyma UI, console, website, compas and whatever. 

https://github.com/kyma-incubator/documentation-component
