### ISSUE TITLE
Page not found is visible before documentation is loaded

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/website#34]
**Description**

Page not found is visible before documentation is loaded. For example here: https://kyma-project.io/docs/latest/components/application-connector#details-deploy-a-new-application-connector

**Expected result**

- [x] No 404 error
- [ ] All milv configs do not have kyma-project.io links blacklisted 

**Actual result**

Page not found
![image](https://user-images.githubusercontent.com/26445970/45736861-84d49380-bbec-11e8-9721-c2bb0c41e80e.png)

**Comment by pkosiec** [comment]
Yup, it might be a problem with Gatsby v2 beta, because it is related to internal routing system. We need to check if updating it solves the problem.

**Comment by akucharska** [comment]
Issue at gatsbyjs created https://github.com/gatsbyjs/gatsby/issues/8781

**Comment by derberg** [comment]
@akucharska please remind Gatsby guys again

**Comment by pkosiec** [comment]
Review: @magicmatatjahu
