### ISSUE TITLE
Broken links in the API section on docs page on kyma website

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/website#35]
Hi,

There are broken links in the API section on docs page on Kyma website. See the screenshot.
 
![links](https://user-images.githubusercontent.com/40662246/45752380-8d8d8f80-bc15-11e8-8ced-e4412de0c2d1.PNG)

See below where these three links should point to:

- See this file for the Events API specification. - https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/assets/eventsapi.yaml

- See this file for the Metadata API specification. - https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/assets/metadataapi.yaml

- See this file for the Connector API specification. - https://github.com/kyma-project/kyma/blob/master/docs/application-connector/docs/assets/connectorapi.yaml

Thank you!

**Comment by lszymik** [comment]
This is duplicated by https://github.com/kyma-project/kyma/issues/783. To be fixed soon.
