### ISSUE TITLE
YouTube Link on https://kyma-project.io/blog/2018/12/10/xxxlutz-video not correctly rendered

### ISSUE THREAD

**Issue by gregorwolf** [kyma-project/website#352]
**Description**

On the page: https://kyma-project.io/blog/2018/12/10/xxxlutz-video there is a YouTube Video linked. Currently it's only shown as:

```
youtube: https://youtu.be/NI4cOWO9HnA
```

**Expected result**

I would think the video should be either directly embedded or linked.

**Actual result**

Not clickable link.

**Steps to reproduce**

Open the website above.

**Troubleshooting**

Used copy & paste.

**Comment by magicmatatjahu** [comment]
@gregorwolf Thanks for reporting the issue! YT render worked correctly, but most likely by fixes related to markdown rendering (tabs), we broken YT rendering. We will deal with it as soon as possible.
