### ISSUE TITLE
Duplicated components in the left-side navigation 

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/website#353]
**Description**

On the [kyma-project.io](https://kyma-project.io/docs/master) in **Docs**,  all components in the left-side navigation are duplicated. It regards the master branch.

**Expected result**

Remove the duplication.

**Attachments**

![Screen Shot 2019-06-10 at 14 40 03](https://user-images.githubusercontent.com/23300533/59195979-baac1480-8b8d-11e9-9cac-a00d11ccc6c4.png)

![Screen Shot 2019-06-10 at 14 44 00](https://user-images.githubusercontent.com/23300533/59196162-35752f80-8b8e-11e9-82cf-7294d2da6b56.png)

**Comment by aerfio** [comment]
It's caused by bug in content-loader, see: 
![image](https://user-images.githubusercontent.com/17271979/59351880-abf56700-8d1f-11e9-9920-debe808612f3.png)
