### ISSUE TITLE
Expose the community repo in kyma website and enable docs component in docs view

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#356]
@derberg commented on [Tue Apr 23 2019](https://github.com/kyma-project/community/issues/266)

Community guidelines, contributing rules, and basically as much as possible from the community repo should be exposed on the website. That includes info on the external SIGs and WGs. That would only encourage the community to contribute to Kyma by making this information easily accessible to everyone.

Examples:
- https://www.minio.io/community.html
- https://kubernetes.io/community/
- https://www.gatsbyjs.org/contributing/

Scope:
- research on how others do it and what solution is the best. 
- review current kyma website structure and propose location of community docs
- understand how building website works and make proper changes in content to prepare for rendering
- review, update and add new content 

Related issue on website: https://github.com/kyma-project/website/issues/286

**Comment by mmitoraj** [comment]
- We need a nice o landing page (overview) that a user sees once clicking the **Community** tab (like for example https://prometheus.io/community/ or https://www.gatsbyjs.org/contributing/).
- I’ve heard @derberg and Ana worked on a text for the Community tab, is it available and where? 
- Is it not a problem to have one more navigation level more than in Kyma Docs? Having Templates in Guidelines topic would require that.
- The most important topics in the Community section would be: 
    - A nice overview of what can be found in the Community tab
    - Contributing.md
    - Code of Conduct
    - Guidelines
    - SIG / WG —> meeting / events + videos from the SIG Core + link to Slack + ling to Github
- We could add a document advising how to create new issues on Github and add it to the Contributing topic.
- Location: a Community tab next to **Docs**, **Blog** and **Roadmap** in the top navigation bar.
- A proposed structured in the excel file attached. -> [Community navigation.xlsx](https://github.com/kyma-project/website/files/3365965/Community.navigation.xlsx)

**Comment by anajankovic** [comment]
Here's the content for the Community landing page.

[Kyma community page content.docx](https://github.com/kyma-project/website/files/3371913/Kyma.community.page.content.docx)

**Comment by mmitoraj** [comment]
Thank you @anajankovic.
