### ISSUE TITLE
Extract documentation view to subdomain

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#361]
**Description**

AC:
- Extract documentation view to subdomain: `docs.kyma-project.io` for example.
  - create `docs` branch for subdomain - see more [here](https://www.netlify.com/blog/2017/11/16/get-full-control-over-your-deployed-branches/)
- Change structure in repository:
  - I prefer `apps` dir with `main` app (including landing page, roadmap, blog) and `docs` and `packages` dir with common components - of course with separate package.json in each one.
  - Use lerna for linking node packages in apps
- Suggest solution for have source of apps in `master` branch. This is very problematic, because netlify have feature called `branch-deploying` - in short: we can have app in subdomain, but this app must be in branch with this same name as subdomain. I would like not to have this same, duplicated code in master and other branch for render markdown for example, or for other components. Separate package in npm is not a solution!
- Think about new layout. My favourite is algolia. They have beautiful styling ❤️ https://www.algolia.com/doc/  Angular also have good https://angular.io/docs

AddAC:
- Thinking about splitting docs views, not per topic, but type in topic, eg: separate view for installation of kyma, separate for architecture etc - eg path `docs.kyma-project.io/master/kyma/installation/#cluster-installation` like in DITA (thanks @bszwarc for idea)

**Reasons**

Separate application for serve documentation is very popular convention in many project. With this approach we will able to separate logic for documentation and other views in kyma-project.io, so we will able to write new functionalities without breaking other views by strange bugs. Also with new layout we will able to serving specs, documentation with other way and styling than serving other markdown content, like blog posts, or in future, community or contributing content.

**Conntected issue**
https://github.com/kyma-project/website/issues/303
https://github.com/kyma-project/kyma/issues/4025

**Comment by derberg** [comment]
@magicmatatjahu I suggest we close this one. For now, we have a solution that only the last 3 versions of docs are published, also we do not really need any apps separation.
