### ISSUE TITLE
Improve content and sections of kyma landing page

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#363]
**Description**

- We need section with list of logos and links to details about how given user uses Kyma on production
- We need to think about adding more credibility to early adopters section, who are they and what are they actually doing with Kyma
- We still need to work on the content and come up with as buzz-word free page as possible
  - some feedback is visible here https://www.reddit.com/r/kubernetes/comments/c21xle/new_kyma_12_release_is_out/. The fact that we are getting all those questions means we really need to address some of them directly on landing page in a clear way
  - I have to admit https://github.com/rancher/rio projects has clear abstract that I like, but I'm not 100% it is because it is really good or I simply know the subject well already.
  - @jcawley5 wrote a blog post that explains what Kyma is and got a lot of positive feedback so we definitely have to look at https://blogs.sap.com/2019/07/08/what-is-kyma/
- have most of the stuff also in main kyma repo readme, especially icons of productive users
- landing page should have a kind of widget that enables you to star a kyma repo on github, like Rio has https://rio.io/
- stretch, while working on content thing also on a script for a video that would explain it.

**Reasons**

The landing page still sounds like a commercial product landing page instead of developer friendly landing page. We also need to add more credibility to the project by mentioning the productive users we already have and a transparent (through PR) way of adding them, so they add themselves to the list and not we do it, so it doesn't look like we fake it (or if we add it, there should be a reference to some testimonial/use case described by particular user)

**Comment by tomekpapiernik** [comment]
If you can allow bits that are little less formal and less tech-heavy, I can offer my way of explaining what Kyma which bases on the analogy that Kyma is a travel power adapter that allows you to plug appliances into the wall around the world, no matter the plug type. Basically comparing the software to a sophisticated adapter with lots of goodies built in.

**Comment by kazydek** [comment]
I'm all for it. If the current intro seems too buzzwordy for the "impartial" readers, let's make it more digestible and descriptive.

**Comment by aerfio** [comment]
Additional AC: please use some kind of tool, like [svgo](https://github.com/svg/svgo), to minify critical SVGs

Previously we had tool that helped us to do this in a form of a [gatsby plugin](https://www.npmjs.com/package/gatsby-plugin-optimize-svgs) , but unfortunately it malformed some svgs, so use it only on critical assets, like that SAAS svg, which takes whole 298kb, in comparison to typical size of ~3kb:
 ![image.png](https://images.zenhubusercontent.com/5ba8c32a4e030d642cf5cc74/f0fa5c09-1274-4fab-b302-4e296de273a8)

**Comment by derberg** [comment]
also, for the landing page and main readme, make sure when we first write Kyma, we provide the way how to pronounce it `Kyma /kee-ma/`. Thanks

**Comment by aerfio** [comment]
We had a meeting, during which we decided that:
- community section is deleted, we have whole /community for that
- buttons from community sections should be tranported to https://kyma-project.io/community/#get-started-get-started-social-media
- we transform "Early Adopters section"
- we need to make "Key features" section less childlish
- "What makes Kyma so special?" is also getting redone with list of cloud-native projects that we use in kyma
- that big header needs to be less buzzwordy
- everything else needs to be less buzzwordy too

**Comment by aerfio** [comment]
Done. `buttons from community sections should be tranported to https://kyma-project.io/community/#get-started-get-started-social-media` - this was ignored as we discussed with TWs that it's not needed
