### ISSUE TITLE
Docs images broken

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/website#379]
**Description**

When viewing the docs on kyma-project.io all the images are not showing up with 404 code.

**Actual result**

![Screen Shot 2019-07-22 at 02 32 12](https://user-images.githubusercontent.com/1930204/61599413-f1fbef80-ac28-11e9-925a-ea0bfdfcd490.png)

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/kyma-project/website/commit/bcea1bfbe521eaadf681a9b17be7936478af5986
