### ISSUE TITLE
Right navigation covers the search results

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/website#422]
**Description**

When you use the search box on `kyma-project.io` the search results window overlaps with the right-hand side navigation. As a result, the navigation covers the search results and makes them unreadable.

**Expected result**

The right-hand navigation does not cover the search results.

**Actual result**

![2019-08-12_14-53-27](https://user-images.githubusercontent.com/23300533/62866625-8b429100-bd11-11e9-8bf4-898148020035.png)

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/kyma-project/website/pull/424
