### ISSUE TITLE
Table content does not appear in search

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/website#432]
**Description**

When performing search, table content in docs does not get found. 

**Expected result**

Table content should appear in search.

**Actual result**

Table content does not appear in search.

**Steps to reproduce**

1. Go to the [Kyma website](https://kyma-project.io/).
2. Click the magnifying glass to search. 
3. Type `insecureSpecDownload`.
4. The search term is not found. 
5. Verify that the term is defined in the [docs](https://github.com/kyma-project/kyma/blob/master/docs/application-connector/05-02-application-registry.md).

**Troubleshooting**

The term is defined in the correct doc. The term does not appear when performing search.

**Comment by magicmatatjahu** [comment]
PR on aloglia repo https://github.com/algolia/docsearch-configs/pull/1040

**Comment by magicmatatjahu** [comment]
Reopen because some data in table still don't appear in search result.

**Comment by magicmatatjahu** [comment]
https://github.com/algolia/docsearch-configs/pull/1050
