### ISSUE TITLE
Automatically adjusted tabs

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/website#443]
**Description**

Kyma website could be enriched with another cool feature. When you change a tab in one section in a document, the tab adjusts automatically in other sections in this doc. It could be useful especially in Kyma cluster installation documentation.

Check the desired behavior here:
https://cloud.google.com/storage/docs/access-control/making-data-public
(when you change tab in one section then it's automatically adjusted in other places).

**Reasons**

Easy context change for a user and better user experience.

**Comment by magicmatatjahu** [comment]
Reopen for creating docs in community repo for new functionality.

**Comment by magicmatatjahu** [comment]
Reopen for creating docs in community repo for new functionality.
