### ISSUE TITLE
Unify the width of table columns on the website

### ISSUE THREAD

**Issue by kazydek** [kyma-project/website#447]
**Description**

Columns in tables that contain long character strings are extremely wide when compared to other columns with text and short content.

See the example from the [Asset Store metrics](https://kyma-project.io/docs/master/components/asset-store/#metrics-asset-metadata-service) below:

![image](https://user-images.githubusercontent.com/40655785/65875485-ac297900-e387-11e9-98b3-009abdf27ae3.png)

**Reasons**

It would be best if we did not have to scroll to view the full table content but have it rendered the same as on [GitHub](https://github.com/kyma-project/kyma/blob/master/docs/asset-store/09-02-asset-metadata-service.md):

![image](https://user-images.githubusercontent.com/40655785/65875815-5a352300-e388-11e9-93ae-2f3dde327bc0.png)

**Comment by derberg** [comment]
we should increase overall content width on kyma-project.io/docs to be able to make documentation width match github again
