### ISSUE TITLE
Modify content of the landing page

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#45]
**Description**

- modify first paragraph to have this new content, headers stays as it is:

 > Kyma allows you to connect applications and third-party services in a cloud-native environment. Use it to create extensions to the existing systems regardless of the language they are written in. Customize extensions with the minimum effort and time devoted to learning their configuration details.

   and at the end link user to main docs section for more details
- modify second paragraph to have this new content, header is `Why Kyma`: https://github.com/kazydek/test_repository/blob/785d2ddf50b557fbf09a42553ce67f00541d7729/landing-page/landing-page.md#why-kyma, at lest the first paragraph
- modify 3rd paragraph, the first component is ok, but next 2 must be changes, one should talk about application connector, the other about serverless. 1st will be about App Connector, 2nd about Serverless and 3rd about Service Catalog (the one we already have)

**Reasons**

Make more understandable content and make sure most important Kyma features are promoted on landing page

**Attachments**

Final version ![screen shot 2018-09-25 at 16 11 41](https://user-images.githubusercontent.com/6995927/46020452-be226d00-c0de-11e8-958d-2a4347035ada.png)

**Comment by kazydek** [comment]
Sth like that?
![kyma-project io_](https://user-images.githubusercontent.com/40655785/46137054-35741000-c249-11e8-908e-b9870c882957.png)

**Comment by kazydek** [comment]
@anajankovic let us know when you consult it whether there is anything to be changed. Thanks!

**Comment by pkosiec** [comment]
Review: @pkosiec @michal-hudy

**Comment by pkosiec** [comment]
Review: @pkosiec
