### ISSUE TITLE
Move internal docs from website to community repo

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#465]
**Description**

Move internal docs like `write-blog-posts`, `banner-modification` from website to community repo and for them create new docsTopic in `guidelines` group.

**Reasons**

At the moment we have docs for writing blog posts etc in website repo, and we don't have any pointing to them in external sources (eg community repo) and it is will be better for external contributors, when they want to contribute (for better community experience) :)

**Comment by derberg** [comment]
moving docs for website repo to community repo breaks our approach to have docs there where the code is and this is why I do not like the idea really.

**Comment by michal-hudy** [comment]
I agree with @derberg. I like to have docs that explain how to contribute with details specific to the particular repository inside the repository, not in a different repo.

In fact, in the community, we should keep only general contribution guides, like forks, squashing, etc. Something like creating a blog post, banner modification, etc. is only related to the website repository, so it should stay in the website repository.
