### ISSUE TITLE
Improve the maintainability and extensibility of website project

### ISSUE THREAD

**Issue by hudymi** [kyma-project/website#472]
**Description**

I have noticed that the contribution to our website is more and more complicated with every PR. Just take a look at the PRs, every feature requires lots of changes in many files. I even noticed that our website is working slow and it is going to be heavier with every new feature. I think we really need to rethink the architecture of this project and be more involved in verifying new functionalities - performance, code complexity and other things. Also, when you look at the code, we have multiple coding styles, it should be unified and the proper documentation with coding standards should be created.

The complexity of the code is currently that big so it is really hard not only to contribute but also make a code review...

**Reasons**

Improve the maintainability and extensibility of the project - it will reduce the entry threshold to the project, and our work will be much easier 😄

**Comment by pbochynski** [comment]
Closed due to inactivity.
