### ISSUE TITLE
Create documentation about flow in website

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#473]
**Description**

AC:
- Create documentation about flow in website
  - create diagram (starting with `content-loader` tool, then gatsby API and `./src` sources) - remember also about netlify lambda for triggering build from `community` and `kyma` webhooks
  - make description to every stage of flow
- Make tutorials:
  - how to add, update existing page (with modals feature)
  - how to extend existing GraohQL nodes
  - how to add new gatsby plugin

**Reasons**

Make more friendly contributing to website for external people and also for internal :)

See also https://github.com/kyma-project/website/issues/472

**Comment by michal-hudy** [comment]
@magicmatatjahu what do you think? Is blog post https://github.com/kyma-project/website/issues/554 enough?

**Comment by valentinvieriu** [comment]
#566 topic might be Related

**Comment by michal-hudy** [comment]
I think that blog post and #566 fulfilled this issue. Let's continue under #566
