### ISSUE TITLE
Banner scrollbar does not autohide on windows

### ISSUE THREAD

**Issue by aerfio** [kyma-project/website#490]
**Description**

When the content is too long then the scrollbar appears _on scroll_, but only on mac, unfortunately not on windows which look ugly. 

**Expected result**

Scrollbar disappears like it should, and it gets appropriate styles.

**Actual result**

It looks bad on windows 😢 

**Steps to reproduce**

**Troubleshooting**

Either solve it on css side (first link on google e.g https://www.filamentgroup.com/lab/scrollbars/) or limit it with [spectral](https://github.com/kyma-project/website/pull/471)

**Comment by aerfio** [comment]
Probably still valid

**Comment by michal-hudy** [comment]
I'm not sure if it is still valid, please reopen it if needed.
