### ISSUE TITLE
Website as a template - architecture design

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#493]
**Description**

High-level requirements. Overview of PICTURE1:
- PRESENTATION LAYER -> Website template to focus only on presentation layer. The presentation layer uses fetching layer API to get needed content for rendering. 
- FETCHING LAYER -> Is an interface that can be easily replaced with custom fetching logic. Default implementation should be a simple HTTP GET request that could support any storage like GH/S3 or any other file server like self-hosted Nginx or Netlify -> PICTURE2
- SOURCE LAYER -> Additional tools for pulling markdown from different repos is separate project is **out of scope** because there are many different use cases and even if later we want to address it, this is not going to be part of the website as a template tool PICTURE3
- DATA LAYER -> where final content fetched in the UI is stored, is **out of scope**

Other requirements:
- No static site generation but real-time rendering like in current docs ui
- Enable modification/configuration of the header and the navigation
- Enable white labeling -> provide your custom CSS
- CLI for running and building website to enable local running for dev purpose and building for production
- Enable possibility to add full new custom landing page or other pages, like we have with roadmap view
- Enable possibility to have multiple views for a different set of docs

---

Desired outcome:
- proposal for the API of the interface for the fetching layer.
- fetching layer must first fetch some kind of config file with links to all the markdown files, like index.yaml with info needed for the building of the navigation. Propose how would such a file look like
- proposal for CLI commands and flags
- propose for configuration file where you define what is in the hearer of the page and other configurable sections
- a proposal on how would one add additional custom pages to the generated website
- how would I configure how many views I get, and what content goes to given view, how would it look like in the config file?

_If we think that what we want to do is already available in tools like https://docusaurus.io/ or something different, then the outcome should be a proposal how to do it differently using existing tools_

**Reasons**
- we want to transform knowhow we got from a website into a reusable template
- we want to use the template to build individual websites for rafter and helm broker
- we want to use the template for rafter as a presentation layer for the documentation use case,  reusable docs-ui

**Attachments**
PICTURE1

![Image from iOS (6)](https://user-images.githubusercontent.com/6995927/68986531-94fff700-0820-11ea-80b2-7fcd46c9fe90.jpg)

PICTURE2

![Image from iOS (5)](https://user-images.githubusercontent.com/6995927/68986532-94fff700-0820-11ea-8c74-65a432995c39.jpg)

PICTURE3

![Image from iOS (8)](https://user-images.githubusercontent.com/6995927/68986529-94676080-0820-11ea-97f9-d478d10ccebd.jpg)

PICTURE4
![Image from iOS (7)](https://user-images.githubusercontent.com/6995927/68986530-94fff700-0820-11ea-82f2-f573c4d4e3bf.jpg)

**Comment by michal-hudy** [comment]
We still need a way to display documentation from different repositories than Kyma

**Comment by michal-hudy** [comment]
Ok, as this is something big and complicated, I would like to start with something simple. Just the generation of the website with documentation. Nothing more. Later, based on this we can start changing it to the template/project.

**Comment by michal-hudy** [comment]
Ideas:
 - as a temporary create separate topic under docs view, display always the latest version

Spike:
 - how to create a separate website for documentations?
 - keep documentation under the `kyma-project.io` domain, not a subdomain. For example `kyma-project.io/repository/rafter`

**Comment by kwiatekus** [comment]
Closing this one in favour of the #603
