### ISSUE TITLE
Write a blog post about integration testing of services in Kubernetes

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#506]
**Description**

It should be a learning story of what are the different solutions and the last section should be about Octopus

Blog content:
* Address most common things people do to run integration tests for their services deployed to Kubernetes
* Explain our use case, what we used first (Helm) and why we had to write something on our own
* What are benefits of Octopus 
* Make it clear Octopus is open for contributions

Technically:
- Should be originally published on https://kyma-project.io/blog/
- Should be later republished to https://medium.com/kyma, best case - using your own accounts, but not a problem to do it with generic Kyma account

**Reasons**

Main reason is building community:
- by sharing our experience
- by sharing the tool we build for our need that others might want to use - https://github.com/kyma-incubator/octopus

**Comment by kazydek** [comment]
@derberg , the blog post is published. I also talked to @anajankovic and she promised to publish it with the generic account on https://medium.com/kyma as well.

**Comment by kazydek** [comment]
It's already published on medium.com: https://medium.com/@kymaopensource/how-we-approached-integration-testing-in-kubernetes-and-why-we-stopped-using-helm-tests-e2d3609e6ed9.
