### ISSUE TITLE
Documentation should be pulled from a branch

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/website#537]
Currently, documentation for the website is pulled from a release tag, not a release branch.
It causes a problem when (in urgent cases) documentation needs to be updated.

Documentation available in the Console is pulled from the release branch so it would be good to have the approach unified for the website as well.

**Comment by michal-hudy** [comment]
Also, release jobs shouldn't be triggered when only documentation is merged to the Kyma release branch.

**Comment by michal-hudy** [comment]
Display documentation for a new release only when the major tag has been created

**Comment by valentinvieriu** [comment]
@bszwarc is this still the case?

**Comment by pbochynski** [comment]
Not valid any more
