### ISSUE TITLE
Write a blog post about Kyma Website (tools, sources & magic behind)

### ISSUE THREAD

**Issue by kazydek** [kyma-project/website#554]
**Description**

Write a blog post explaining the story behind https://kyma-project.io/:
- Which tools we used and why (Gatsby, Netlify)
- How our implementation differs from how normally Gatsby is used
- Views: Docs, Blog, Community, Roadmap, Landing page:
    - Where the sources are taken from
    - How the building flow / process looks like and what triggers views to rebuild
    - How to add sth to every view &  add references to available templates, documents, instructions that would help the community to contribute to the website content

**Comment by valentinvieriu** [comment]
@kazydek How about we split this into a couple of blog posts ( a mini series ) and align it with the [jamstackconf](https://jamstackconf.com/), so maybe we can get some exposure from the people attending there?

**Comment by valentinvieriu** [comment]
@kazydek is it possible to document this in the README too? #566

**Comment by kazydek** [comment]
@valentinvieriu, sure that's a good idea to add this info to the README as well - I added #566 to our team's backlog. As for the blog post - this one is supposed to be very generic and introductory. We could later see what the readers are most interested in and come up with further ones that would be more technical and focus on a chosen feature/view/aspect.

**Comment by kazydek** [comment]
Written, published - over and out ;)
