### ISSUE TITLE
Adapt documentation-component to single blog post page

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/website#561]
**Description**

Documentation and community pages use our `documentation-component` with functionalities like right navigation (table of content) with scroll-spy, copy to clipboard code blocks, open images in new browser tab with full size, anchors, tabs etc. Unfortunately, blog view uses old implementation of our markdown rendered without mentioned functionalities.

AC:
- Adapt documentation-component to single blog post page.
- Add share buttons to facebook, twitter, reddit, linkedin etc on single blog post page.

Stretch: 
- Think also about changing styles for main blog post pages. 

**Reasons**

**Attachments**

**Comment by pbochynski** [comment]
@kwiatekus Please check it.
