### ISSUE TITLE
Stop using latest tag and enable versioning for documentation

### ISSUE THREAD

**Issue by derberg** [kyma-project/website#57]
**Description**

- Enable support for versioning in UI
  - should be possible to link to latest and not specific version
  - drop down with multiple versions should indicate which one is latest
  - check if we can get rid of `latest` in the URL
- Make sure we base docs versioning on releases only. Release marked as latest is the one that should be displayed by default
- for now we do not care about pre-release

**Reasons**

Kyma started doing releases, different releases will contain different changed docs, we need to support versioning of docu then.

**Comment by pkosiec** [comment]
Review: @pkosiec @magicmatatjahu
