### ISSUE TITLE
CSS style is inlined on all pages

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#574]
**Description**

All the css is inlined on all pages, making all the pages bigger and affecting the download time.

**Expected result**

CSS should be shared, to allow caching, and making the html smaller

**Actual result**

The CSS is inlined, and we use an empty style.js file and also a non used `<style data-href="/styles.813eff898f24f85008c0.css">`

**Steps to reproduce**

Open any page and view source. Observe network traffic there is no CSS loaded

**Comment by michal-hudy** [comment]
- Investigate the root cause for that if it will be a big issue then please contact @valentinvieriu or me

**Comment by valentinvieriu** [comment]
@magicmatatjahu I'm still seeing a lot of inline css on the page. Isn't there a way to share some of that too? In the case of documentation pages, all of the css there is shared on all pages. right now it seems that is namespaces for every page, and still inlined

**Comment by valentinvieriu** [comment]
This is a valid issue
