### ISSUE TITLE
Avoid using png files, use smaller files format

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#578]
**Description**

We have areas of our website where we use png's
![image](https://user-images.githubusercontent.com/478866/82441373-1c634700-9a9e-11ea-95c3-4118bcc2e8ab.png)

**Expected result**

We should optimize images to speed up the website download

**Actual result**

We have quite big PNG's on couple of our pages

**Steps to reproduce**

Navigate to[https://kyma-project.io/community/guidelines/repository/]( https://kyma-project.io/community/guidelines/repository/) and check images

**Comment by kwiatekus** [comment]
After Kyma 2.0 there is a plan to rewrite kyma website from scratch.
@valentinvieriu do you want to keep this one open? If so, please re-open
