### ISSUE TITLE
Google does not index the /docs

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#580]
**Description**
It seems that Google does not index the `/docs` section because of the confusion in the `robots.txt`
At this moment we have docs/latest in the sitemap.xml and in the navigation url we point to /docs that is ignored by the robots.txt

![image](https://user-images.githubusercontent.com/478866/82478397-25b9d700-9ad1-11ea-981e-a3aa213144a5.png)

**Expected result**

We should be consistent and use /docs/latest or remove the robots.txt ignore

**Actual result**

we are linking to a page that is ignored in robots.txt ( /docs/ )

**Comment by kazydek** [comment]
Same as mentioned in https://github.com/kyma-project/community/issues/462 - if we decide to go for `/docs/latest`, we would also need to update all links in docs.
