### ISSUE TITLE
Create Blog Post - How to install Kyma locally without MiniKube

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#583]
Would be great to explore more lightweight ways of installing Kyma locally instead of using Minikube. Maybe using [Kind](https://kind.sigs.k8s.io/) or [k3s](https://k3s.io/), [k3d](https://k3d.io/) or other more lightweight solutions

**Comment by valentinvieriu** [comment]
It seems there is a [pull request ](https://github.com/kyma-project/kyma/pull/7930) on this already, and is aimed for 1.14

**Comment by michal-hudy** [comment]
Hm... I think this is rather for @pbochynski and @piotrmsc as they are working with installation topic 😄

**Comment by piotrmsc** [comment]
@valentinvieriu @michal-hudy for me blog post can be created once we will have desired way of installing kyma. I wouldn't create a blog post that we will try to use k3s/kind or anything else. Let's communicate once we will have some concrete examples, proved by WG POCs and further discussions :)

**Comment by valentinvieriu** [comment]
> @valentinvieriu @michal-hudy for me blog post can be created once we will have desired way of installing kyma. I wouldn't create a blog post that we will try to use k3s/kind or anything else. Let's communicate once we will have some concrete examples, proved by WG POCs and further discussions :)
Yes I agree, this was added to keep track of this topic
