### ISSUE TITLE
KCP documentation as a separate node on the website

### ISSUE THREAD

**Issue by klaudiagrz** [kyma-project/website#593]
**Description**

Until now, Compass documentation was stored both in the `kyma-incubator/docs` repo, and in the `kyma/docs` repo in order to have it displayed on the website. As we [separate Compass from Kyma](https://github.com/kyma-incubator/compass/blob/82eef46dfca601e431a9fa37fbe9ec6bda9de01f/docs/internal/proposals/separate-compass/separate-compass.md) and introduce a new Kyma Central Plane (KCP) apprach, we have to reflect it in the documentation that is displayed on the website. The idea is to have KCP docs displayed in parallel to the Kyma docs as a separate node on the website (see the attachment). After selecting the node (Kyma or KCP), the appropriate list of components should appear in the left navigation panel.

**Reasons**

KCP documentation must be displayed on the website but also separated from the Kyma documentation. 

**Attachments**

This would be a perfect place for the additional KCP node:

![Screen Shot 2020-07-07 at 11 26](https://user-images.githubusercontent.com/35192450/86760104-44eed280-c045-11ea-8ee1-56b0851f985a.png)

**Related issues:**

#493

**Comment by klaudiagrz** [comment]
This would be also a good place for the Compass documentation if we are going to store it on the website. In such a case, we'd have three main nodes:
- Kyma
- KCP
- Compass

**Comment by pbochynski** [comment]
@klaudiagrz Please close the ticket or move it to the next milestone.

**Comment by kwiatekus** [comment]
KCP has an own navigation node selectable from header
