### ISSUE TITLE
Adjust and restructure the content on homepage to align with manifesto and personas

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#608]
**Description**
We need to restructure and redesign the Homepage, so that it communicate more clearly the new focus of Kyma ( is an application runtime ) and allows for focused messaging towards the 2 target personas about key advantages of using Kyma.

Secondary Goals:

- We want to promote and inspire team members and individual contributors
- We want to encourage external companies to become Contributors
- We want to improve SEO by having deeper relevant links to our documentation and tutorials
- We want our users to quickly jump and try it out – have a fast quick start

**Reasons**

We need to align to our new [manifesto](https://github.com/kyma-project/community/blob/master/manifesto/) and [personas](https://github.com/kyma-project/community/blob/master/manifesto/personas.md)

**Comment by Disper** [comment]
Two questions identified during today's workshop:
- Understand what are Kyma key features in the new approach
- Understand what the "application runtime" approach means and how it differs from "extensibility platform"

**Comment by klaudiagrz** [comment]
Ok, so I have gathered some feedback from my team and according to them, from the developer's perspective, the website should limit the content and focus on the use case examples. As we've already mentioned, we need to grab the user's attention; otherwise, they will just get bored and close the page. So extensive reading is a no-no here, I'd say. 

From what I've learned from the feedback, our website could be structured in such a way:
1. A few **general sentences** that Kyma is the environment where you can deploy your applications and that it comes with ready-to-use logging, tracing, and so on. 
2. A **video with a use case** example (PB once showed a very clear example of how to use Kyma with Wordpress).
3. Link to the **tutorials** with few words of encouragement to try out Kyma on your own. 

I don't know whether this feedback answers any questions, but it may be taken into consideration while working on the structure.

**Comment by valentinvieriu** [comment]
Here is a Proposed Wireframe on how to structure the content on the page. Please keep in mind that this has no design attached, even if some sections are in color. It underlines only a proposed structure of the page.

The mental flow of the page: 
Why ? +---------> How we do it? +---------> Main usecases Persona 1 +---------> Main Usecases Persona 2 +---------> How I install it? +--------->  Who is the team behind? +---------> Who is using Kyma, and how?

![Desktop](https://user-images.githubusercontent.com/478866/89879683-9699f800-dbc3-11ea-8d27-652189294c5f.jpg)

**Comment by kazydek** [comment]
@valentinvieriu I'm attaching a proposal for the **Why Kyma?** and **Personas** sections - that's an initial ("placeholder") version, feel free to propose changes and update it.

```
Kyma is a Kubernetes-based platform on which you can create and deploy microservices and functions - either as standalone applications or extensions for the existing enterprise systems.

## Why Kyma

### Extensibility platform

If you are looking for cloud-native ways to extend your enterprise products, Kyma is a secure and tested environment you can rely on. First, connect external APIs and ensure a stable event flow between the external or built-in services and your own applications. Then, start molding your own code into microservices and functions that extend your applications' logic.

### Application runtime

Build standalone Kubernetes applications from scratch. Kyma is also an application runtime that is scalable, secure, and reliable. It allows you to develop microservices-based solutions in any language and run them on Kubernetes clusters from a cloud provider of your choice.

### Operational support

Kyma ensures smooth Day-2 support for the standalone applications and extensions you'll create. Thanks to numerous CNCF open-source projects that come preconfigured with Kyma, you can easily monitor the performance of your microservices and functions, scan logs for errors, and upgrade your solutions painlessly.

## Personas (& key reasons to use Kyma)

### Matthew (cloud-native software engineer)

- I seek innovation. Kyma not only draws inspiration from CNCF projects but also fills the missing gaps between them by tailoring such solutions as external application connectivity. It constantly evolves and improves, and I like it a lot.

- I need flexible solutions. With Kyma, I have the freedom I need to write k8s apps in a language and IDE of my choice. I can also deploy my source code on a cloud provider I prefer.

- I want to focus purely on coding. Kyma does the "dirty" job for me by providing the whole infrastructure and covering such areas as security, monitoring, and tracing.

### Sebastian (tech lead)

- I seek time-saving & cost-effective solutions. Kyma allows me to design easy, fast, and lightweight extensions for my complex enterprise applications.

- I need a solution that supports diverse business cases rather than utilizes a single pattern. Kyma gives me the architecture design that is complete but modular at the same time. Thanks to its high configurability, I'm able to plug in, unplug, and replace subcomponents whenever and however I wish.

- I like to play it safe and can't take much risk by investing in startups. Kyma is actively maintained, has solid foundations, and already some success stories to rely on.
```

**Comment by kazydek** [comment]
@evilyeti could you take a look at our proposal above? It aligns with what we discussed (3 concepts) but pls see it's ok or sth needs to be improved. Thanks a lot in advance :)

**Comment by kwiatekus** [comment]
For Matthew  consider sth like :
```
For me Kyma helps me focus on coding. It is an extra integration tissue on top of k8s that exposes that helps me consume APIs and Events from external systems. 
```

**Comment by klaudiagrz** [comment]
I'm reviewing the content on Kyma runtime that is published at the Discovery Center and I thought that it might be quite helpful while working on the content for the website. The presentation also contains two simple use-cases that might be used for the short video that we have discussed during the last call (I especially like the one with Facebook - everyone knows Facebook). See for yourself: 
https://discovery-center.cloud.sap/protected/index.html#/missiondetail/3252/3281

**Comment by valentinvieriu** [comment]
The content structure is reflected in the design issue #609 
This general issue is considered closed, we will address content related topics per component level as we will develop them
