### ISSUE TITLE
Kyma overview docu improvement request

### ISSUE THREAD

**Issue by pnpavlov** [kyma-project/website#62]
Hello,
**Description**

 https://github.com/kyma-project/website/blob/017701cde4ae72023709419b616b5710cf8eaff8/static/documentation/latest/root/kyma/content.json#L10  states that "The entire solution is containerized and runs on a Kubernetes cluster hosted in the Microsoft Azure cloud environment. "

Also the links to "Local Kyma installation and Cluster Kyma installation" are not working in the website. I would assume they work in the markdown file, but are not rendered correct.

**Expected result**
Shouldn't this text be more kubernetes cluster provider neutral? Something like "The entire solution is containerized and runs on a Kubernetes cluster hosted on a cloud provider or on-premise, even on minikube."

I would expect to be able to click on the mentioned "Local Kyma installation and Cluster Kyma installation" guides.

Regards,
Pavel

**Comment by pkosiec** [comment]
Hi @pnpavlov! Thank you for reporting this. Last week we were working on improving the Overview section and today we released a new version of docs. Could you please take a look now? The improvements should be noticeable: https://kyma-project.io/docs/latest/root/kyma#overview-overview

Also, I've tested links in Local/Cluster installation section (e.g. Kubernetes operator, jq, etc.) and they work fine for me. Can you give an example of a broken link?

**Comment by pkosiec** [comment]
Recently we modified the source of docs on `kyma-project.io`. When I was writing the previous comment, all docs have been taken from `master` branch of `kyma` repository. A week later or so we switched to show docs from release branches only.

That's why your comment is now again valid - we need to cherry pick new documentation changes alongside new release. But I'm not sure when it will happen.

**Comment by pkosiec** [comment]
Hi @PavelPavlov46, new version of Kyma has been just released, and in the same time we updated the docs. Take a look: https://kyma-project.io/docs/#

I'm closing this issue as it is no longer valid. If you have more suggestions/bugs regarding docs, please report them straight in kyma-project/kyma repository. Thanks!
