### ISSUE TITLE
Kyma Manifesto Homepage Component

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#624]
**Description**

As Mathew and Sebastian ([personas](https://github.com/kyma-project/community/blob/master/manifesto/personas.md)) I would like to understand at a glance what is the Kyma project. This should be a clear statement that clearly communicates what is Kyma and what's the problem space that we are solving.

**Acceptance Criterias**

- The component follows the designs attached ( Desktop and mobile )
- The text is SEO relevant and is SSR
- The text will be used as Meta Description for the whole website, and as main description for other OpenGraph/Twitter tags
- The content ( text ) of the component does not need to be final. This user story is about the html/css/js creation                                                                                                    
- Clicking on the chevron will advance to the next section - smooth animation scrolling if possible
**Attachments**

![image](https://user-images.githubusercontent.com/478866/92363150-5d38a780-f0f1-11ea-81af-82356b72ca89.png)
![image](https://user-images.githubusercontent.com/478866/92363190-6b86c380-f0f1-11ea-83fd-1ddadd373b7e.png)

**Comment by kwiatekus** [comment]
@valentinvieriu ca we close it?
