### ISSUE TITLE
Kyma Key Features component for Homepage

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#625]
**Description**

As Mathew and Sebastian ([personas](https://github.com/kyma-project/community/blob/master/manifesto/personas.md)) I would like to understand what are Kyma's top 3 features and what problems do they solve. 

**Acceptance Criteria**

- The component follows the designs attached ( Desktop and mobile ) and responsive bhaviour
- The text is SEO relevant and is SSR
- we are using SVG as vector graphics and minimised to reduce size
- The content ( text ) of the component does not need to be final. This user story is about the html/css/js creation                                                                                                    

**Attachments**

![image](https://user-images.githubusercontent.com/478866/92363346-a25cd980-f0f1-11ea-8f7b-1004cb2d4b52.png)
![image](https://user-images.githubusercontent.com/478866/92363530-e8b23880-f0f1-11ea-83d1-6e03b8db8d29.png)

**Comment by kwiatekus** [comment]
@valentinvieriu ca we close it?
