### ISSUE TITLE
Broken ordered list in "Cluster Kyma installation"

### ISSUE THREAD

**Issue by tomekpapiernik** [kyma-project/website#63]
The website UI does not render the ordered list in the "Cluster Kyma installation" document correctly. All of the points on the list are "1." instead of consecutive numbers. The list renders with no issues when viewing the document in GitHub. 

[This](https://github.com/kyma-project/kyma/blob/master/docs/kyma/docs/032-gs-cluster-installation.md) is the document in question. 
The list constitutes most of the "Installation" paragraph.

**Comment by derberg** [comment]
actually the source is broken, maybe numbers are there but the flow is broken. Did you try first fixing the source with 3 spaces like this to get a proper indentation in numbering? 
sample https://github.com/derberg/kyma/commit/f3cdbed7f1e9542bc73b77a49c2071dd2dd40a12

**Comment by tomekpapiernik** [comment]
You're right Lukasz, I didn't check that. Closing this issue.
