### ISSUE TITLE
Used By component - for New Homepage Redesign

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/website#630]
**Description**

As Mathew and Sebastian ([personas](https://github.com/kyma-project/community/blob/master/manifesto/personas.md)) I would like to know what companies are using Kyma and get a high level understanding what problems does it solves for them. 

**Acceptance Criteria**

- The component follows the designs attached ( Desktop and mobile ) and responsive behaviour ( see wide screen version for background stretching )
- The cards become a Carousel on Mobile. Cards can will have fixed height ( the height of the longest card ) in the carousel. Swiping moves the carousel.
- The text is SEO relevant and is SSR
- All items will be available on the page. Load more will just show them all.
- we are using minimised SVGs as background graphics
- Read More button is available if external link to a blog post is provided
- The size ( height ) of the cards is dynamic, and synchronised with the nearby card ( side by side ), to have the same height in desktop view
- The content ( text ) of the component does not need to be final. This user story is about the html/css/js creation. We will use our current logos and text.                                                                                                   

**Attachments**

![image](https://user-images.githubusercontent.com/478866/93181036-3ead5e80-f738-11ea-8d0e-f1301f3f85a5.png)
![image](https://user-images.githubusercontent.com/478866/93181355-a9f73080-f738-11ea-96c0-e4512c5666b2.png)

![image](https://user-images.githubusercontent.com/478866/93895733-7005cb80-fcf0-11ea-9fbc-505b47d40490.png)

**Comment by aerfio** [comment]
Note: after we merge all sections we also need to update docs for adopters

**Comment by kwiatekus** [comment]
@valentinvieriu can we close it?
