### ISSUE TITLE
Relative path to the *.pdf files are not working

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/website#665]
**Description**

The website should store pdf files in the assets folder but it doesn't.

**Expected result**

The PDF file should be copied to the `assets` folder and be open when someone is trying to view it

**Actual result**

`404: Page not found.`

**Steps to reproduce**

Go to the [Corporate contributor license agreement](https://kyma-project.io/community/contributing#contributing-rules-contributing-rules-corporate-contributor-license-agreement) and try to open the `Corporate Contributor License Agreement` file.

**Comment by magicmatatjahu** [comment]
Add here https://github.com/kyma-project/website/blob/master/gatsby/node-api/nodes/onCreateNode/copyAssets.ts#L37 pdf extension.
