### ISSUE TITLE
Slack invitation is not working

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/website#673]
@eldad87 commented on [Sat Feb 06 2021](https://github.com/kyma-project/kyma/issues/10537)

Hi,
I tried to join your Slack channel, unfortunately the invitation on your official site has expired.

Please advise,
Thanks!

**Comment by tgorgol** [comment]
I just tried all the links I found on the website (navbar, footer, and community page) and they seem to be working fine.

@eldad87 could you please confirm if the problem still persists and specify which link were you using?

**Comment by kwiatekus** [comment]
Thanks @tgorgol for checking. 
I was also able to join ( join by email path )
 @eldad87 Please reopen with more details which link ( and which browser ? ) does not work for you
