### ISSUE TITLE
Broken photo from the blog post 

### ISSUE THREAD

**Issue by anajankovic** [kyma-project/website#75]
**Description**

When i share the blog post link https://kyma-project.io/blog/release-notes-041 on social media channels there is no a preview blog post photo or Kyma logo if a blog post doesn't contain the photo.  

See the photo below

![image](https://user-images.githubusercontent.com/40662246/47006176-9c446500-d135-11e8-9380-425da575f9ff.png)

Can you, please fix this bug?

As i mentioned above it would be good to have the preview blog post photo or Kyma logo if a blog post doesn't contain the photo. 

Thank you,
Ana

**Comment by derberg** [comment]
don't use png for kyma but svg

**Comment by pkosiec** [comment]
@derberg 
> twitter:image
> A URL to a unique image representing the content of the page. (...) The image will be cropped to a square on all platforms. JPG, PNG, WEBP and GIF formats are supported. Only the first frame of an animated GIF will be used. SVG is not supported.

**Comment by pkosiec** [comment]
Unfortunately there is no way to put an image from blog post into the sharing metadata. That's why I will just put a standard logo for every link shared from kyma-project.io.

**Comment by mjasinski5** [comment]
review: @akucharska @magicmatatjahu

**Comment by anajankovic** [comment]
When i share the kyma blog post link on Twitter the Kyma logo is still not showing. Can you, please, check this again?

Thanks!

**Comment by derberg** [comment]
@anajankovic but this issue is not yet closed and PR not yet merged
