### ISSUE TITLE
Old links in Helmbroker

### ISSUE THREAD

**Issue by elchead** [kyma-project/website#752]
**Description**
In Helm Broker section:
https://kyma-project.io/docs/components/helm-broker/
The link for helm-repo-urls is outdated and now included in the values.yaml here:
https://github.com/kyma-project/kyma/blob/main/resources/helm-broker/values.yaml

**Area**

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

**Comment by pbochynski** [comment]
Can you just provide a PR with the fix? We should avoid such issues :)
