### ISSUE TITLE
Update description and shortDescription fileds in UI.json

### ISSUE THREAD

**Issue by kazydek** [kyma-project/website#77]
**Description**

These lines require an update after the content of the main page was changed and, among other things, `framework` was removed from the overall Kyma landing page description:
- "shortDescription": "Cloud-native application development framework",
- "description": "Kyma is an open source, cloud-native application development framework. It provides the last mile capabilities that a developer needs to build a cloud-native application"

File: https://github.com/kyma-project/website/blob/master/src/locales/en/UI.json

**Comment by derberg** [comment]
dup #89
