### ISSUE TITLE
Website displays content that's been removed from GH

### ISSUE THREAD

**Issue by majakurcius** [kyma-project/website#799]
**Description**

For some time now, our Website has been displaying documentation that has long been gone from GitHub/modified. Basically it’s not in sync with what’s on GitHub.
For instance, compare the Application Connectivity tutorials [on GitHub](https://github.com/kyma-project/kyma/tree/main/docs/03-tutorials/00-application-connectivity) vs [on the Website](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/).
This could be a **potential release blocker** ❗  as it displays documentation that’s no longer valid.

A few examples:
- the [Bind an Application to a Namespace](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/ac-03-application-mapping/) tutorial, that has been removed
- the [Register a Service tutorial](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/ac-03-register-manage-services/), which was renamed and modified and is now duplicated on the Website
   ![image](https://user-images.githubusercontent.com/53601578/144385464-0eb34930-ea7c-47b8-8b30-731743152f92.png)

**Expected result**

The Website displays the exact same documentation that's in our [Kyma GitHub repository](https://github.com/kyma-project/kyma/tree/main/docs).

**Actual result**

The Website displays documentation that has been removed or old versions of documentation that has been modified.
For example, several tutorials were removed, and the remaining ones' content and names changed, so now there are tutorials that are duplicated (one version is the one that's been removed, the other is the "new version"). 
This happens only on the Website. GitHub displays documentation correctly. 

**Steps to reproduce**

Compare the list of documents and their content (for example, Application Connectivity tutorials) [on GitHub](https://github.com/kyma-project/kyma/tree/main/docs/03-tutorials/00-application-connectivity) and [on the Website](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/), and observe that they differ.

**Attachments**

- [Application Connectivity tutorials on GitHub](https://github.com/kyma-project/kyma/tree/main/docs/03-tutorials/00-application-connectivity):
   ![image](https://user-images.githubusercontent.com/53601578/144385049-f3925d0d-fc27-45d8-8ec1-43f42e1f8a77.png)

-  [Application Connectivity tutorials  on the Website](https://kyma-project.io/docs/kyma/latest/03-tutorials/00-application-connectivity/):
   ![image](https://user-images.githubusercontent.com/53601578/144385077-72030085-32de-4cb6-ba32-53f2add60211.png)

**Related issue**
https://github.com/kyma-project/website/issues/800

**Comment by pbochynski** [comment]
It is not a release blocker, but still important.
