### ISSUE TITLE
White screen after searching "Kyma Dashboard" on the website

### ISSUE THREAD

**Issue by grego952** [kyma-project/website#806]
**Description**
When I try to access Kyma Dashboard from the search bar all I get is a white page. Only after I reload the page it works fine. It happens only when I look for the Kyma Dashboard. I checked it on Chrome and Safari.

**Expected result**
When I click the search button I should be directed right away to the Kyma Dashboard page.

**Actual result**
When I look for Kyma Dashboard:
![Zrzut ekranu 2021-12-8 o 07 43 08](https://user-images.githubusercontent.com/62639546/145167224-65fc281f-3884-4d8a-b693-3a3e5a724371.png)

and press the search icon, all I get is:
![Zrzut ekranu 2021-12-8 o 07 43 35](https://user-images.githubusercontent.com/62639546/145167255-70404868-facc-41ad-a1be-19331e0a2d0e.png)

**Comment by kwiatekus** [comment]
Its same for `Kyma CLI` topic.
Looks like algolia returns url with `ui` and `cli` in small letters 
```
https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/ui/ui-02-cli/#documentation-content
https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/ui/ui-01-gui/#documentation-content
```
but the routable path consist of capital letters `UI` and `CLI`
```
https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/ui/ui-02-CLI/#documentation-content
https://kyma-project.io/docs/kyma/latest/01-overview/main-areas/ui/ui-01-GUI#documentation-content
```

If I refresh the page chrome fixes it by capitalising the problematic part and the route is found

**Comment by kwiatekus** [comment]
The changes are pushed.
Unfortunately this cannot be fixed on website w/o an actual github release.
This is because Algolia index provides links to `/latest/` release - not main :(
The problem with search result link will be part of next kyma release.

For now, please refresh the page after you see a blank screen
