### ISSUE TITLE
Page listed in the search bar wasn't found

### ISSUE THREAD

**Issue by Lyczeq** [kyma-project/website#880]
**Description**
When I type `serv` in the Algolia Search bar and click on the first option(Serverless periodically restarting) there's an information `404: Page not found.`. What is more, the title of the page is `Undefined`. The [file](https://github.com/kyma-project/kyma/tree/main/docs/04-operation-guides/troubleshooting/serverless) exists in the Kyma repository docs, so there's definitely problem with website rather than documentation. If I go to the page manually instead of using a search bar, everything works fine.

**Expected result**
The Search bar should correctly link to the pages in the documentation.

**Actual result**
The Search doesn't link to the pages correctly. In some cases it works well, but in others not.

**Steps to reproduce**
1. Go to the website and type `serv` in the search bar. 
2. Click on the first option (Serverless periodically restarting).
3. You should see the information `404: Page not found.` and the title of the page should be `Undefined`.

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/56163767/191008224-14c7a11b-3b93-4887-b4f3-c69e0f4a9165.png">

**Troubleshooting**

**Comment by valentinvieriu** [comment]
this should be closed by https://github.com/kyma-project/website/pull/928
