### ISSUE TITLE
Search results not found

### ISSUE THREAD

**Issue by lautoma** [kyma-project/website#916]
**Description**
Trying to use the search functionality on the Kyma-project.io website
Basic scenario: open homepage, click on the search icon, write something, see (preview) results in the list, click on one of the results to go to the page.

**Expected result**
When I click on a result item I am taken to the right page. 

**Actual result**
404 not found received for several search results. For example: 
- searching for "Serverless"  - https://kyma-project.io/docs/kyma/latest/04-operation-guides/troubleshooting/svls-05-serverless-periodically-restarting/#documentation-content 
- searching for "expose service" - https://kyma-project.io/docs/kyma/latest/03-tutorials/00-api-exposure/apix-05-expose-and-secure-workload-istio/#expose-your-workload-using-a-virtual-service
- "istio" - https://kyma-project.io/docs/kyma/latest/04-operation-guides/operations/smsh-01-istio-disable-sidecar-injection/#documentation-content

There surely are more, perhaps they could be checked.

**Comment by valentinvieriu** [comment]
The search index has been updated. @lautoma pls check again

**Comment by lautoma** [comment]
@valentinvieriu I've just checked and it's working fine.
