### ISSUE TITLE
Missing migration script to 2.9

### ISSUE THREAD

**Issue by franpog859** [kyma-project/website#920]
**Description**

Kyma 2.9.X is already out. When you go to our landing page -> [Docs](https://kyma-project.io/docs/kyma/latest/) -> [Migration Guide 2.8-2.9](https://kyma-project.io/docs/kyma/latest/migration-guide-2.8-2.9) -> [2.8-2.9-cleanup-psp.sh](https://kyma-project.io/docs/kyma/latest/assets/docs/kyma/latest/assets/2.8-2.9-cleanup-psp.sh) - it says 404: Page not found. Well, that looks like a critical problem to me. Currently, no one can upgrade their open-source Kyma clusters to the 2.9 version
<img width="800" alt="Screenshot 2022-12-02 at 09 14 12" src="https://user-images.githubusercontent.com/32485355/205247009-d8aafae9-e0ef-4517-bbfc-063f8d96f4fa.png">

**Expected result**

Provided in the description

**Actual result**

Provided in the description

**Steps to reproduce**

Provided in the description

**Comment by mrCherry97** [comment]
@grego952 will fix the link: https://github.com/kyma-project/kyma/blob/release-2.9/docs/assets/2.8-2.9-cleanup-psp.sh

**Comment by Sawthis** [comment]
It is working now. Kyma 2.9.2 had to be released.
