### ISSUE TITLE
Create a blogpost for deprecated Istio sidecar injection annotation

### ISSUE THREAD

**Issue by strekm** [kyma-project/website#932]
**Description**

Create a blogpost informing Kyma users about Istio sidecar injection annotation being deprecated in favour of labels. Deprecation notice was introduced with 1.16 Istio version and blogpost should be published with Kyma 2.10 release. Blogpost should use examples how to find Pods using annotations (using kubectl command or istioctl). Part of blogpost should be example how to change annotation to label on pod template of deployment. Text should contain examples of Pod with annotation and after the change with label. 

**Area**
* Service Mesh

**Reasons**

**Assignees**

@kyma-project/technical-writers

**Attachments**

https://github.com/kyma-project/kyma/issues/16374

**Comment by nataliasitko** [comment]
The blog post is ready: https://kyma-project.io/blog/2022/12/30/deprecation-of-istio-sidecar-injection-annotation/
